name: saga
version: 0.1.0.0

default-extensions:
- OverloadedStrings

extra-source-files:
- README.md
- LICENSE

dependencies:
  - array
  - base
  - bytestring
  - prettyprinter
  - containers
  - transformers
  - mtl
  - haskeline

library:
  source-dirs: src
  build-tools:
  - alex
  - happy

tests:
  saga-test:
    main:                Spec.hs
    source-dirs:         tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - saga
    - hspec