name: saga
version: 0.1.0.0


language: GHC2021

default-extensions:
  - OverloadedStrings

extra-source-files:
  - README.md
  - LICENSE

dependencies:
  - array
  - base
  - bytestring
  - containers
  - transformers
  - mtl
  - haskeline
  - pretty-simple
  - effectful
  - sbv


library:
  source-dirs: 
    - src
  ghc-options:
    - -fdefer-typed-holes

  build-tools:
  - alex
  - happy

tests:
  saga-test:
    main:                Spec.hs
    source-dirs:         tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - saga
    - hspec